services:
  api-gateway:
    image: api-gateway
    build:
      context: .
      dockerfile: api-gateway/Dockerfile

  hosting:
    image: hosting
    build:
      context: .
      dockerfile: Hosting/Dockerfile

  procode.hosting:
    image: procode.hosting
    build:
      context: .
      dockerfile: ProCode.Hosting/Dockerfile

